name: New Commit
on: [push]
jobs:
  Update-Readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: git
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
      - run: ruby "${{ github.workspace }}/commit-monster.rb"
